title: Technical Documentation
description: Technical Documentation Flanders Smart Data Space
remote_theme: just-the-docs/just-the-docs@v0.5.3

url: https://just-the-docs.github.io

favicon_ico: "/assets/images/favicon.ico"

callouts:
  note:
    title: Note
    color: yellow
  highlight:
    title: Tip
    color: green


# External navigation links
nav_external_links:
  - title: Linked Data Interactions Core Building Blocks
    parent: core
    url: https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/core/index
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: Linked Data Interactions Orchestrator
    parent: ldio
    url: https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/index
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: Linked Data Interactions For Apache Nifi
    parent: ldi-nifi
    url: https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldi-nifi/index
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false


# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-9F4LJXRX6T
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Define Jekyll collections
collections:
  introduction:
    permalink: "/:collection/:path"
    output: true
  quickstart:
    permalink: "/:collection/:path"
    output: true
  release:
    permalink: "/:collection/:path"
    output: true


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

just_the_docs:
  collections:

    introduction:
      name: Introduction to LDES
    quickstart:
      name: Quickstart
    core:
      name: Linked Data Interactions Core Building Blocks
    ldio:
      name: Linked Data Interactions Orchestrator
    ldi-nifi:
      name: Linked Data Interactions for Apache NiFi
    release:
      name: Release Management


enable_copy_code_button: true




footer_content: "Technical Documentation of the building blocks developed in the frame of the <a href=\"https://www.vlaanderen.be/vlaamse-smart-data-space-portaal\">Flanders Smart Data Space</a>."


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Contribute on GitHub"
# gh_edit_repository: "https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions" # the github URL for your repo
gh_edit_branch: "develop" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"


